
version: "3"

services:

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 8890:9000

    volumes:
        - data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped\
volumes:
  data:

  nginxproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt 


networks:
  default:
    name: m_network  